// 後台管理路由
export default [
  {
    path: '/',
    name: 'admin-home',
    redirect: '/signin',
  },
  {
    path: '/signin',
    name: 'admin-signin',
    component: () => import('../../views/Tailadmin/Auth/Signin.vue'),
    meta: {
      title: 'Sign In',
      menuGroup: 'Others',
      menuLabel: 'Signin',
      menuParent: 'Authentication',
      icon: 'PlugInIcon',
      order: 901,
    },
  },
  {
    path: '/signup',
    name: 'admin-signup',
    component: () => import('../../views/Tailadmin/Auth/Signup.vue'),
    meta: {
      title: 'Sign Up',
      menuGroup: 'Others',
      menuLabel: 'Signup',
      menuParent: 'Authentication',
      icon: 'PlugInIcon',
      order: 902,
    },
  },
  {
    path: '/dashboard',
    name: 'admin-dashboard',
    component: () => import('../../layouts/Tailadmin/default.vue'),
    children: [
      {
        path: '',
        name: 'admin-ecommerce',
        component: () => import('../../views/Ecommerce.vue'),
        meta: {
          title: 'eCommerce Dashboard',
          menuGroup: 'Menu',
          menuLabel: 'Ecommerce',
          menuParent: 'Dashboard',
          icon: 'GridIcon',
          order: 1,
        },
      },
      {
        path: 'calendar',
        name: 'admin-calendar',
        component: () => import('../../views/Tailadmin/Others/Calendar.vue'),
        meta: {
          title: 'Calendar',
          menuGroup: 'Menu',
          menuLabel: 'Calendar',
          icon: 'CalenderIcon',
          order: 2,
        },
      },
      {
        path: 'profile',
        name: 'admin-profile',
        component: () => import('../../views/Tailadmin/Others/UserProfile.vue'),
        meta: {
          title: 'User Profile',
          menuGroup: 'Menu',
          menuLabel: 'User Profile',
          icon: 'UserCircleIcon',
          order: 3,
        },
      },
      {
        path: 'form-elements',
        name: 'admin-form-elements',
        component: () => import('../../views/Tailadmin/Forms/FormElements.vue'),
        meta: {
          title: 'Form Elements',
          menuGroup: 'Menu',
          menuLabel: 'Form Elements',
          menuParent: 'Forms',
          icon: 'ListIcon',
          order: 101,
        },
      },
      {
        path: 'basic-tables',
        name: 'admin-basic-tables',
        component: () => import('../../views/Tailadmin/Tables/BasicTables.vue'),
        meta: {
          title: 'Basic Tables',
          menuGroup: 'Menu',
          menuLabel: 'Basic Tables',
          menuParent: 'Tables',
          icon: 'TableIcon',
          order: 201,
        },
      },
      {
        path: 'blank',
        name: 'admin-blank',
        component: () => import('../../views/Tailadmin/Pages/BlankPage.vue'),
        meta: {
          title: 'Blank Page',
          menuGroup: 'Menu',
          menuLabel: 'Black Page',
          menuParent: 'Pages',
          icon: 'PageIcon',
          order: 301,
        },
      },
      {
        path: 'error-404',
        name: 'admin-error-404',
        component: () => import('../../views/Tailadmin/Errors/FourZeroFour.vue'),
        meta: {
          title: '404 Page',
          menuGroup: 'Menu',
          menuLabel: '404 Page',
          menuParent: 'Pages',
          icon: 'PageIcon',
          order: 302,
        },
      },
      {
        path: 'line-chart',
        name: 'admin-line-chart',
        component: () => import('../../views/Tailadmin/Chart/LineChart/LineChart.vue'),
        meta: {
          title: 'Line Chart',
          menuGroup: 'Others',
          menuLabel: 'Line Chart',
          menuParent: 'Charts',
          icon: 'PieChartIcon',
          order: 601,
        },
      },
      {
        path: 'bar-chart',
        name: 'admin-bar-chart',
        component: () => import('../../views/Tailadmin/Chart/BarChart/BarChart.vue'),
        meta: {
          title: 'Bar Chart',
          menuGroup: 'Others',
          menuLabel: 'Bar Chart',
          menuParent: 'Charts',
          icon: 'PieChartIcon',
          order: 602,
        },
      },
      {
        path: 'alerts',
        name: 'admin-alerts',
        component: () => import('../../views/Tailadmin/UiElements/Alerts.vue'),
        meta: {
          title: 'Alerts',
          menuGroup: 'Others',
          menuLabel: 'Alerts',
          menuParent: 'Ui Elements',
          icon: 'BoxCubeIcon',
          order: 701,
        },
      },
      {
        path: 'avatars',
        name: 'admin-avatars',
        component: () => import('../../views/Tailadmin/UiElements/Avatars.vue'),
        meta: {
          title: 'Avatars',
          menuGroup: 'Others',
          menuLabel: 'Avatars',
          menuParent: 'Ui Elements',
          icon: 'BoxCubeIcon',
          order: 702,
        },
      },
      {
        path: 'badge',
        name: 'admin-badge',
        component: () => import('../../views/Tailadmin/UiElements/Badges.vue'),
        meta: {
          title: 'Badge',
          menuGroup: 'Others',
          menuLabel: 'Badge',
          menuParent: 'Ui Elements',
          icon: 'BoxCubeIcon',
          order: 703,
        },
      },
      {
        path: 'buttons',
        name: 'admin-buttons',
        component: () => import('../../views/Tailadmin/UiElements/Buttons.vue'),
        meta: {
          title: 'Buttons',
          menuGroup: 'Others',
          menuLabel: 'Buttons',
          menuParent: 'Ui Elements',
          icon: 'BoxCubeIcon',
          order: 704,
        },
      },
      {
        path: 'images',
        name: 'admin-images',
        component: () => import('../../views/Tailadmin/UiElements/Images.vue'),
        meta: {
          title: 'Images',
          menuGroup: 'Others',
          menuLabel: 'Images',
          menuParent: 'Ui Elements',
          icon: 'BoxCubeIcon',
          order: 705,
        },
      },
      {
        path: 'videos',
        name: 'admin-videos',
        component: () => import('../../views/Tailadmin/UiElements/Videos.vue'),
        meta: {
          title: 'Videos',
          menuGroup: 'Others',
          menuLabel: 'Videos',
          menuParent: 'Ui Elements',
          icon: 'BoxCubeIcon',
          order: 706,
        },
      },
    ],
  },
]
